markdown: redcarpet
pygments: true
permalink: /posts/:title
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
title : Zuhao
production_url : http://wanzuhao.com
description: "Done is better than perfect."
disqus_shortname: zuhao-blog
analytics: UA-21036797-1
domain_name: wanzuhao.com
author :
  name : Zuhao Wan
  github : zuhao
  twitter : wanzuhao
  email: wanzuhao@gmail.com
