markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Zuhao
production_url : http://wanzuhao.com
description: "Done is better than perfect."
disqus_shortname: zuhao-blog
analytics: UA-21036797-1
domain_name: wanzuhao.com
author :
  name : Zuhao Wan
  github : zuhao
  twitter : wanzuhao
  email: wanzuhao@gmail.com
